import { ClientType } from "@/utils/types/clients";
import PicturePlaceholder from "../../../public/img/placeholder.jpg";


export const clients: ClientType[] = [
  {
    id: 1,
    name: "ABC Corporation",
    logo: PicturePlaceholder,
    sector: "Corporate",
    description: "A leading provider of innovative corporate solutions.",
    website: "https://www.abccorp.com",
    email: "contact@abccorp.com",
    phone: "+63-2-123-4567",
    address: "123 Ayala Avenue, Makati City, Metro Manila, Philippines",
    projectsCompleted: 12,
    partnershipStartDate: "2018-06-15",
  },
  {
    id: 2,
    name: "Municipality of Sample",
    logo: PicturePlaceholder,
    sector: "Government",
    description: "A government body serving the citizens of Sample Municipality.",
    website: "https://www.samplecity.gov.ph",
    email: "info@samplecity.gov.ph",
    phone: "+63-44-987-6543",
    address: "Municipal Hall, Sample Town, Bulacan, Philippines",
    projectsCompleted: 8,
    partnershipStartDate: "2017-03-10",
  },
  {
    id: 3,
    name: "Sample Private School",
    logo: PicturePlaceholder,
    sector: "Education",
    description: "An esteemed private school focused on academic excellence.",
    website: "https://www.sampleprivateschool.edu.ph",
    email: "admissions@sampleprivateschool.edu.ph",
    phone: "+63-32-223-4455",
    address: "456 Education Lane, Cebu City, Cebu, Philippines",
    projectsCompleted: 5,
    partnershipStartDate: "2020-09-05",
  },
  {
    id: 4,
    name: "Tech Innovators Inc.",
    logo: PicturePlaceholder,
    sector: "Technology",
    description: "Pioneers in cutting-edge tech solutions for businesses.",
    website: "https://www.techinnovators.com.ph",
    email: "support@techinnovators.com.ph",
    phone: "+63-2-888-1234",
    address: "789 Innovation Drive, Bonifacio Global City, Taguig, Metro Manila, Philippines",
    projectsCompleted: 15,
    partnershipStartDate: "2016-11-20",
  },
  {
    id: 5,
    name: "Green Earth Initiative",
    logo: PicturePlaceholder,
    sector: "Non-Profit",
    description: "A non-profit organization dedicated to environmental conservation.",
    website: "https://www.greenearth.org.ph",
    email: "hello@greenearth.org.ph",
    phone: "+63-48-456-7890",
    address: "321 Eco Way, Puerto Princesa City, Palawan, Philippines",
    projectsCompleted: 25,
    partnershipStartDate: "2014-04-22",
  },
  {
    id: 6,
    name: "Sample General Hospital",
    logo: PicturePlaceholder,
    sector: "Healthcare",
    description: "A state-of-the-art hospital offering world-class healthcare services.",
    website: "https://www.samplehospital.org.ph",
    email: "info@samplehospital.org.ph",
    phone: "+63-45-867-5309",
    address: "654 Health Boulevard, Angeles City, Pampanga, Philippines",
    projectsCompleted: 10,
    partnershipStartDate: "2019-01-15",
  },
  {
    id: 7,
    name: "Metro Real Estate Group",
    logo: PicturePlaceholder,
    sector: "Real Estate",
    description: "Experts in property development and management.",
    website: "https://www.metrorealestate.com.ph",
    email: "sales@metrorealestate.com.ph",
    phone: "+63-2-333-2222",
    address: "789 Property Road, Pasig City, Metro Manila, Philippines",
    projectsCompleted: 7,
    partnershipStartDate: "2015-07-01",
  },
  {
    id: 8,
    name: "Retail Solutions Co.",
    logo: PicturePlaceholder,
    sector: "Retail",
    description: "Helping retailers improve operations and customer experiences.",
    website: "https://www.retailsolutions.com.ph",
    email: "contact@retailsolutions.com.ph",
    phone: "+63-34-111-4444",
    address: "258 Commerce Street, Bacolod City, Negros Occidental, Philippines",
    projectsCompleted: 14,
    partnershipStartDate: "2013-09-25",
  },
  {
    id: 9,
    name: "Smith & Brothers Law Firm",
    logo: PicturePlaceholder,
    sector: "Legal",
    description: "Providing expert legal counsel for businesses and individuals.",
    website: "https://www.smithbrotherslaw.com.ph",
    email: "info@smithbrotherslaw.com.ph",
    phone: "+63-2-222-3333",
    address: "147 Justice Avenue, Quezon City, Metro Manila, Philippines",
    projectsCompleted: 9,
    partnershipStartDate: "2018-05-12",
  },
  {
    id: 10,
    name: "Creative Marketing Agency",
    logo: PicturePlaceholder,
    sector: "Marketing",
    description: "Specialists in crafting impactful marketing campaigns.",
    website: "https://www.creativemarketing.com.ph",
    email: "hello@creativemarketing.com.ph",
    phone: "+63-2-444-5555",
    address: "369 Branding Boulevard, Makati City, Metro Manila, Philippines",
    projectsCompleted: 18,
    partnershipStartDate: "2021-02-10",
  },
];